updated pointerEquals to avoid using System.identityHashCode
DanySK/javalib-java7 pull request #1
Opened 2016-11-25 17:37 UTC by gscaparrotti

System.identityHashCode is affected by a bug which reduce performances,
so it's better not to use it at the moment

2016-11-29 10:40 UTC, DanySK requested changes

2016-11-29 10:40 UTC, DanySK commented on src/main/java/org/danilopianini/lang/HashUtils.java
> +     * In most JVM implementations this is actually a pointer comparison.
Remove this line

2016-11-29 10:40 UTC, DanySK commented on src/main/java/org/danilopianini/lang/HashUtils.java
> +     * Nevertheless, this is not guaranteed: handle with care
Remove this line

2016-11-30 17:18 UTC, gscaparrotti commented
the new commit should be ok

2016-12-05 14:42 UTC, merged